/*
 * helloworld_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package models_pkg



/*
 * Structure for the custom type HelloWorldResponse
 */
type HelloWorldResponse struct {
    Message         *string         `json:"message,omitempty" form:"message,omitempty"` //TODO: Write general description for this field
}
