/*
 * helloworld_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package configuration_pkg



type CONFIGURATION interface {
        DefaultServerUrl()  *string
        SetDefaultServerUrl(defaultServerUrl *string)
}   
/*
 * Factory for the CONFIGURATION interaface returning CONFIGURATION_IMPL
 */
func NewCONFIGURATION() CONFIGURATION{
    configuration := new(CONFIGURATION_IMPL)
    defaultserverurl := "http://www.example.com"
    configuration.SetDefaultServerUrl(&defaultserverurl) 
    return configuration
}